apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2026-04-23T10:39:06Z"
  labels:
    kubernetes.io/metadata.name: dev
  name: dev
  resourceVersion: "192584"
  uid: c0fa9ec4-fb7d-474d-be72-b510afe0be3a
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
