apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: dev
spec:
  ports:
    - port: 80 # port the SERVICE listens on (cluster-facing)
      protocol: TCP
      targetPort: 80 # port the CONTAINER listens on
  selector:
    app: webapp
  type: NodePort
