apiVersion: v1
kind: Secret
metadata:
  name: my-secret # req
  namespace: default # opt
  labels: # opt
    app: nginx
type:
  Opaque # opt (def)
  # Opaque (generic)
  # kubernetes.io/tls
  # kubernetes.io/dockerconfigjson
  # kubernetes.io/service-account-token
  # bootstrap.kubernetes.io/token
data: # opt*
  # all values base64
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
  tls.crt: LS0t... # for tls type
  tls.key: LS0t...
stringData: # opt (plain text)
  api_key: "my-key" # k8s encodes it
immutable: false # opt


# Use in Pod:
# envFrom:
#  - secretRef:
#      name: my-secret
