apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: pod
spec:
  containers:
  - image: busybox
    name: pod
    command: ["sh","-c","echo SERVER_NAME:${APP_ENV} && echo LOG_LEVEL:${LOG_LEVEL} && echo APP_PORT:${APP_PORT} && sleep 3600"]

    env:
      - name: APP_ENV
        valueFrom:
          configMapKeyRef:
            key: APP_ENV
            name: app-config
      - name: LOG_LEVEL
        valueFrom:
            configMapKeyRef:
              key: LOG_LEVEL
              name: app-config
      - name: APP_PORT
        valueFrom:
          configMapKeyRef:
            key: APP_PORT
            name: app-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
