apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        # without configmap we needed to define the environment variables like hardcoded values (not best practice)
        # env:
        #   - name: SERVER_NAME
        #     value: "IAP-Prod"

        # usage of configmap
        envFrom:
          - configMapRef:
              name: app-config
        resources: 
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
