apiVersion: v1
kind: PersistentVolume
metadata:
  name: busybox-pvc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/pvc/logs

# this is the path inside the node filesystem for persisting data