apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-secret-volume
spec:
  serviceName: mysql-secret-volume
  replicas: 1
  selector:
    matchLabels:
      app: mysql-secret-volume
  template:
    metadata:
      labels:
        app: mysql-secret-volume
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
          - containerPort: 3306

        envFrom:
          - secretRef:
              name: db-secret-volume

        volumeMounts:
          # ✅ MySQL data (PVC)
          - name: mysql-data
            mountPath: /var/lib/mysql

          # ✅ Secret as files
          - name: secret-vol
            mountPath: /etc/secrets
            readOnly: true

      volumes:
        - name: secret-vol
          secret:
            secretName: db-secret-volume

  volumeClaimTemplates:
    - metadata:
        name: mysql-data   # ✅ separate name
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi