apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-configmap-as-volume
  name: busybox-configmap-as-volume
spec:
  containers:
    - image: busybox
      name: busybox-configmap-as-volume
      command: ["sh", "-c", "cat /etc/config/app.properties; sleep 3600;"]
      volumeMounts:
        - mountPath: /etc/config
          name: app-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: app-config
      configMap:
        name: app-config
