apiVersion: v1
data:
  app.properties: |-
    ENV=Production
    PORT=8080
    # cat > app.properties <<EOF
    # ENV=production
    # PORT=8080
    # DB_HOST=mysql-service
    # DB_PORT=3306
    # EOF
kind: ConfigMap
metadata:
  name: configmap-from-file
