apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
    - image: busybox
      name: busybox
      command:
        ["sh", "-c", "echo 'Persist Data!' > /storage/data.txt; sleep 3600; "]
      volumeMounts:
        - mountPath: /storage
          name: my-storage
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc
